vault/__init__.py
import logging
import os
from datetime import datetime
from logging.handlers import SMTPHandler, RotatingFileHandler
from flask import Flask, Blueprint

from flask_babel import Babel, lazy_gettext as _1
from flask_bootstrap import Bootstrap
from flask_login import LoginManager, current_user
from flask_mail import Mail
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import and_, between

from config import Config
from vault.admin import CustomAdminView

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = _1('Authorized Users Must Log In To Access This Page')
mail = Mail()
bootstrap = Bootstrap()
babel = Babel()



def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.app_context().push()

    db.init_app(app)
    #db.create_all()

    migrate.init_app(app, db)
    login.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)
    babel.init_app(app)

    @app.context_processor
    def utility_processor():
        def get_authorizations():
            users = User.query.all()
            user_auth = {u.username:u.authorization.name for u in users}
            target_user = current_user
            try:
                return user_auth[target_user.username]
            except AttributeError:
                return 'READ_ONLY'
        return dict(get_authorizations = get_authorizations())

    if __name__ != '__main__':
        gunicorn_logger = logging.getLogger('gunicorn.error')
        app.logger.handlers = gunicorn_logger.handlers
        app.logger.setLevel(gunicorn_logger.level)

    with app.app_context():

        from vault.errors import bp as errors_bp
        app.register_blueprint(errors_bp)

        from vault.auth import bp as auth_bp
        app.register_blueprint(auth_bp, url_prefix='/auth')

        from vault.main import bp as main_bp
        app.register_blueprint(main_bp)

        from vault import models
        from vault.models import User, Employee, EmployeeReport, ShiftReport, Authorization, Role
        from vault.admin import Admin, AuthorizationView, EmployeeView, EmployeeReportView, RoleView, ShiftReportView, UserView
        from flask_admin.contrib.sqla import ModelView
        # admin_ctrl = Admin(app, name="Volstead's Vault", index_view=AdminView(ShiftReportView, db.session, url='/admin', endpoint='admin'))
        # admin.init_app(app=app)

        # admin_ctrl.add_view(AdminView(Authorization, db.session))
        # admin_ctrl.add_view(AdminView(Employee, db.session))
        # admin_ctrl.add_view(AdminView(EmployeeReport, db.session))
        # admin_ctrl.add_view(AdminView(Role, db.session))
        # admin_ctrl.add_view(AdminView(User, db.session))





        # admin_bp = Blueprint('admin', __name__, static_folder='static', template_folder='templates')

        # BELOW DID NOT WORK - MISSING SOME INTEGRATION BETWEEN ITSELF AND BLUEPRINTS IT SEEMS
        # admin.add_view(view=AuthorizationView)
        # admin.add_view(view=EmployeeView)
        # admin.add_view(view=EmployeeReportView)
        # admin.add_view(view=RoleView)
        # admin.add_view(view=ShiftReportView)
        # admin.add_view(view=UserView)

        # BELOW WORKED - how to customize?
        admin_ctrl = Admin(app, index_view=CustomAdminView())
        admin_ctrl.add_view(ModelView(Authorization, db.session))
        admin_ctrl.add_view(ModelView(Employee, db.session))
        admin_ctrl.add_view(ModelView(EmployeeReport, db.session))
        admin_ctrl.add_view(ModelView(Role, db.session))
        admin_ctrl.add_view(view=ModelView(name='Shift Reports', model=ShiftReport, session=db.session))
        admin_ctrl.add_view(view=ModelView(name='Users', model=User, session=db.session))

        # admin.add_view(ModelView(User, db.session))




        if not app.debug and not app.testing:

            if app.config['MAIL_SERVER']:
                auth = None

                if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                    auth = (app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'])
                secure = None

                if app.config['MAIL_USE_TLS'] is True:
                    secure = True

                mail_handler = SMTPHandler(
                    mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                    fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                    toaddrs=app.config['ADMINS'][0],
                    subject="Volstead's Vault Vexed",
                    credentials=auth,
                    secure=secure)

                mail_handler.setLevel(logging.ERROR)
                app.logger.addHandler(mail_handler)

            if app.config['LOG_TO_STDOUT']:
                stream_handler = logging.StreamHandler()
                stream_handler.setLevel(logging.INFO)
                app.logger.addHandler(stream_handler)

            else:
                if not os.path.exists('logs'):
                    os.mkdir('logs')
                file_handler = RotatingFileHandler('logs/volsteads.log', maxBytes=10240, backupCount=10)
                file_handler.setFormatter(logging.Formatter(
                    '%(asctime)s %(levelname)s: %(message)s '
                    '[in %(pathname)s:%(lineno)d]'))
                file_handler.setLevel(logging.INFO)
                app.logger.addHandler(file_handler)

            app.logger.setLevel(logging.INFO)
            app.logger.info("Volstead's Vault startup")

        # from vault import models
        # from vault.models import User, Employee, EmployeeReport, ShiftReport, Authorization, Role

        @login.user_loader
        def load_user(user_id):
            return User.query.get(int(user_id))

        def earnings_for_year(emp: Employee, year: int):

            # shift_range_start = datetime.strptime(f'12/31/{str(year-1)}', '%m/%d/%Y')
            shift_range_start = datetime.strptime(f'6/20/{str(year)}', '%m/%d/%Y')
            shift_range_end = datetime.strptime(f'12/30/{str(year)}', '%m/%d/%Y')

            # EmployeeReport.query.filter_by(employee_id=emp.id).join(ShiftReport, and_(EmployeeReport.c.shift_id == shift.c.id, shift_range_start < ShiftReport.c.start_date < shift_range_end))

            # return EmployeeReport.query.join(ShiftReport, EmployeeReport.shift_id == ShiftReport.id).filter_by(employee_id=11)
            # return ShiftReport.query.join(EmployeeReport, EmployeeReport.shift_id == ShiftReport.id).filter_by(employee_id=11)
                # .filter_by( ShiftReport.start_date < shift_range_end).all()
                # .filter_by(EmployeeReport.id == emp.id).sum(EmployeeReport.cred_tips)
            # return EmployeeReport.query.filter_by(employee_id=emp.id).join(ShiftReport, EmployeeReport.shift_id==ShiftReport.id).filter_by(shift_range_start < ShiftReport.start_date < shift_range_end)
            return db.session.query(EmployeeReport).join(ShiftReport).\
                filter(EmployeeReport.employee_id==emp.id).filter(ShiftReport.start_date.between(shift_range_start, shift_range_end))

        emp = Employee.query.filter_by(last_name='BOLINE').first()
        print('emp -> ')
        print(emp)
        print('before earnings_for_year()')
        reports = earnings_for_year(emp, 2019)
        for report in reports:
            print(report)
        print('after earnings_for_year()')
        # admin = Admin.init_app(app)

        return app

vault/main/__init__.py
from flask import Blueprint
bp = Blueprint('main', __name__)
from vault.main import routes

vault/main/routes.py
import time
import itertools
from datetime import datetime, timedelta
from decimal import Decimal, ROUND_HALF_UP

import gspread
from flask import session, flash, render_template, copy_current_request_context, url_for, request, g
from flask_babel import get_locale
from flask_login import current_user, login_required
from flask_user import roles_required
from numpy import linspace
from retrying import retry

from vault import db, models
from vault.g_sheet import GoogleSheetsMgr
from vault.main import bp
from vault.main.employee_data_controller import EmployeeDataController
from vault.main.shift_data_controller import ShiftDataController
from vault.models import Employee



def get_staff_data(role_id):
    staff = db.session.query(Employee).filter(Employee.role_id == role_id)
    staff_data = []
    for emp in staff:
        new_emp_data_ctrl = EmployeeDataController(first_name=emp.first_name, last_name=emp.last_name, tip_role=emp.default_tip_role)
        staff_data.append(new_emp_data_ctrl)
    return staff_data

shift_hours_range = linspace(0.0, 9.0, num=19, retstep=True)
g_sheet = GoogleSheetsMgr()
g_sheet.tips_sheet = g_sheet.get_worksheet()

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_online = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())

def redirect_url(default='auth.login'):
    return request.args.get('next') or request.referrer or url_for(default)

def stringify_date(date: datetime):
    return date.strftime('%A %B %d %Y')

def list_of_emp(emp_list) -> bool:
    if isinstance(emp_list, list):
        for emp_data in emp_list:
            if not isinstance(emp_data, EmployeeDataController):
                return False
        return True
    return False

def get_shift_date():
    today = datetime.today()
    if int(datetime.now().strftime('%H')) >= 17:
       return today
    else:
        yesterday = today - timedelta(days=1)
        return yesterday



#=====================================================================================================================
# START REPORT @ '/' '/index
#=====================================================================================================================

@bp.route('/', methods=['GET', "POST'"])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def start_report():

    if request.method == 'GET':
        primary_staff_data = get_staff_data(role_id=1)
        alt_staff_data = get_staff_data(role_id=2)
        shift = ShiftDataController(staff=primary_staff_data, alt_staff=alt_staff_data)
        return render_template('start_report.html', float_range=shift_hours_range, shift=shift)


    if request.method == 'POST':
        rf = request.form
        primary_staff_data = get_staff_data(role_id=1)
        alt_staff_data = get_staff_data(role_id=2)
        shift = ShiftDataController(staff=primary_staff_data, alt_staff=alt_staff_data)

        for emp in itertools.chain(shift.staff, shift.alt_staff):
            if models.Employee.query.filter_by(first_name=emp.first_name).filter_by(last_name=emp.last_name).count() == 0:
                new_emp_record = models.Employee(first_name=emp.first_name, last_name=emp.last_name)
                db.session.add(new_emp_record)
            hours_tag_id = emp.first_name + emp.last_name + '-hours'
            hours = float(rf[hours_tag_id])
            if hours > 0.0:
                shift.shift_hours += hours
                emp._shift_hours = hours
                staff_role_tag_id = emp.first_name + emp.last_name + '-radio'
                emp._tip_role = rf[staff_role_tag_id]
                if emp.tip_role == 'SUPPORT':
                    emp._tip_hours = Decimal(emp.shift_hours * 0.65).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)
                    shift.tip_hours += emp.tip_hours
                if emp.tip_role == 'SERVICE':
                    emp._tip_hours = emp.shift_hours
                    shift.tip_hours += emp.tip_hours

        db.session.commit()

        for denom in shift.cash_subtotals:
            shift.cash_subtotals[denom] = float(rf[denom])
            shift.cash_tip_pool += float(rf[denom])

        shift.cash_tip_wage = float(Decimal(shift.cash_tip_pool / shift.tip_hours).quantize(Decimal('.01'), rounding=ROUND_HALF_UP))
        shift.cred_tip_pool = float(rf['report-tips'])
        shift.cred_tip_wage = float(Decimal(shift.cred_tip_pool / shift.tip_hours).quantize(Decimal('.01'), rounding=ROUND_HALF_UP))

        for emp in itertools.chain(shift.staff, shift.alt_staff):
            emp._cash_tips = float(Decimal(Decimal(shift.cash_tip_wage) * Decimal(emp.tip_hours)).quantize(Decimal('.01'), rounding=ROUND_HALF_UP))
            emp._cred_tips = float(Decimal(Decimal(shift.cred_tip_wage) * Decimal(emp.tip_hours)).quantize(Decimal('.01'), rounding=ROUND_HALF_UP))

        shift.start_date = get_shift_date()

        session['shift'] = shift.serialize()

        if shift.shift_hours and shift.cash_tip_pool and shift.cred_tip_pool:
            return render_template('view_report.html', shift=shift, stringify_date=stringify_date)

        else:
            error = "Total hours, total cash tips, and total credit tips must be non zero."
            return render_template('start_report.html', float_range=shift_hours_range, error=error)


#=====================================================================================================================
# REGISTER USER @ '/register_user'
#=====================================================================================================================

@bp.route('/register_user', methods=['GET', 'POST'])
@roles_required('Admin')
@login_required
def register_user():
    return render_template('register.html')


#=====================================================================================================================
# SUBMIT REPORT @ '/submit_report'
#=====================================================================================================================

@bp.route('/submit_report', methods=['GET','POST'])
@login_required
def submit_report():

    @copy_current_request_context
    @retry(wait_exponential_multiplier=1000, wait_exponential_max=10000, stop_max_attempt_number=35)
    def write_to_g_sheets(shift_ctrl):
        g_sheet_mgr = GoogleSheetsMgr()
        g_sheet_mgr.tips_sheet = g_sheet_mgr.get_worksheet()
        g_sheet_mgr.insert_new_row_for_shift(shift_ctrl)
        g_sheet_mgr.check_previous_subtotals(shift_ctrl.start_date)
        g_sheet_mgr.end_of_period_check(shift_ctrl.start_date)
        return render_template('report_archived_confirmation.html', daily_report=shift_ctrl)

    shift_data = session['shift']

    shift = ShiftDataController(
        staff         =[EmployeeDataController(first_name=e['first_name'], last_name=e['last_name'], tip_role=e['tip_role'], shift_hours=float(e['shift_hours']),   tip_hours=float(e['tip_hours']), cash_tips=float(e['cash_tips']), cred_tips=float(e['cred_tips'])) for e in shift_data['staff']],
        alt_staff     =[EmployeeDataController(first_name=a['first_name'], last_name=a['last_name'], tip_role=a['tip_role'], shift_hours=float(a['shift_hours']), tip_hours=float(a['tip_hours']), cash_tips=float(a['cash_tips']), cred_tips=float(a['cred_tips'])) for a in shift_data['alt_staff']],
        shift_hours   = float(shift_data['shift_hours']),
        tip_hours     = float(shift_data['tip_hours']),
        cash_tip_pool = float(shift_data['cash_tip_pool']),
        cred_tip_pool = float(shift_data['cred_tip_pool']),
        cash_tip_wage = float(shift_data['cash_tip_wage']),
        cred_tip_wage = float(shift_data['cred_tip_wage']),
        start_date    = get_shift_date())

    primary_staff_data = get_staff_data(role_id=1)
    alt_staff_data = get_staff_data(role_id=2)

    if list_of_emp(primary_staff_data) and list_of_emp(alt_staff_data) and isinstance(shift, ShiftDataController):
        new_shift_report = models.ShiftReport.populate_fields(shift)
        db.session.add(new_shift_report)
        db.session.commit()
        new_shift_id = new_shift_report.id

        for emp_report in itertools.chain(shift.staff, shift.alt_staff):

            current_emp = models.Employee.query.filter_by(first_name=emp_report.first_name).filter_by(last_name=emp_report.last_name).first()
            new_employee_report = models.EmployeeReport.populate_fields(employee_report=emp_report, shift_id=new_shift_id, employee_id=current_emp.id)
            if new_employee_report.shift_hours > 0.0:
                db.session.add(new_employee_report)

        db.session.commit()

        try:
            write_to_g_sheets(shift)
        except gspread.exceptions.APIError:
            msg = 'Resource Unavailable Temporarily, Wait 5 Minutes before navigating away from this page.'
            flash(msg)
            time.sleep(301)
            write_to_g_sheets(shift)

        return render_template('report_archived_confirmation.html', daily_report=shift)
    return render_template('404.html')


#=====================================================================================================================
# PRIVACY POLICY @ '/privacy_policy
#=====================================================================================================================

@bp.route('/privacy_policy', methods=['GET'])
def privacy_policy():
    return render_template('privacy_policy.html')

vault/templates/429.html
{% extends 'layout.html' %}

{% block page_content %}
    <h1>Too Many Requests</h1>
    <h4>Please try again after {{ retry_after }}.</h4>
    <p><a href="{{ url_for('main.start_report') }}">Back</a></p>
{% endblock %}

vault/templates/index.html
{% extends 'layout.html' %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    <div id="index-div">
        {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.login') }}">Login</a>
        {% else %}
            <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

vault/templates/layout.html
{% extends "bootstrap/base.html" %}

{% block head %}
    {{ super() }}
    <title>Volstead's Vault {% block title %} {% endblock %}</title>

    {% block metas %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}

    {% block styles %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel=stylesheet
              href={{ url_for('static',
              filename='css/template_style.css') }}>
        <link href="https://fonts.googleapis.com/css?family=Niconne|Federo|Megrim|Codystar|Monofett|Bungee+Outline|Gugi|Poiret+One|Montserrat+Subrayada|Text+Me+One|Chathura"
              rel="stylesheet">

    {% endblock %}
{% endblock %}



{% block content %}

    {% with messages = get_flashed_messages() %}
        {% if messages %}
             <div class="row" id="flash-wrapper">
                <div class="col err-msg-wrapper center-block text-center" id="flash-parent">
                    <ul class='flashes center-block'>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <div class="col-12 px-0" id="image-div">
        <img class="img-fluid w-100 h-100" id="banner-image" src="{{ url_for('static', filename='img/marquee-Volstead.jpg') }}">
    </div>
    <nav class="navbar navbar-expand-md">
        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon navbar-dark"></span>
        </button>
        <div class="navbar-collapse offcanvas-collapse" id="sidebar-div">
            <ul class="navbar-nav flex-container text-center">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id="nav-username" href="#">
                            {% if '@' in current_user.username %}
                                {{ current_user.username.split('@')[0]|upper }}
                            {% else %}
                                {{ current_user.username|upper }}
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{{ url_for("main.start_report") }}'>START REPORT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">LOGOUT</a>
                    </li>
                    {% if current_user.username %}
                        {% if 'Admin' in get_roles  %}
                            <li class="nav-item" id="dd-nav-item">
                                <div class="dropdown" id="admin-dropown-div">
                                    <a class="btn dropdown-toggle" role="button" id="nav-dd-btn" data-toggle="dropdown">ADMIN</a>
                                    <div class="dropdown-menu" id="admin-dd-menu">
                                        <a class="dropdown-item nav-link dd-content" href="#">ADD USER</a>
                                        <a class="dropdown-item nav-link dd-content" href='#' {# {{ url_for("admin.users.update") }} #}>MODIFY USER</a>
                                        <a class="dropdown-item nav-link dd-content" href='#' {# {{ url_for("admin.users.delete") }} #}>86 USER</a>
                                        <a class="dropdown-item nav-link dd-content" href='#' {# {{ url_for("admin.gsheet") }} #}>SHIFT REPORTS</a>
                                    </div>
                                </div>
                            </li>
                        {% endif %}
                    {% endif %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href='{{ url_for("auth.login") }}'>LOGIN</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#" role="button">LINK 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">LINK 2</a>
                </li>
            </ul>
        </div>
    </nav>



    <div class="content col-12 flex-container" id="layout-content-div">
{#        <img class="content-image" src="../static/img/vol_lib_port.jpg">#}
{#        <div class="content-wrapper">#}
            {% block page_content %}{% endblock %}
{#        </div>#}
    </div>

{% endblock %}


{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/offcanvas.js') }}"></script>
{% endblock %}

vault/templates/login_user.html
{% extends 'layout.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    <div class="form-wrapper">
        <form method="post" action="{{ url_for('main.start_report') }}" id="user-login-form">
            <div class="username">
                {{ form.username(placeholder='username') }} {{ form.username.label }}
                {% if form.username.errors %}
                    <ul class="errors">
                        {% for error in form.username.errors %}
                            <li>{{ error }}</li>
                        {{ endfor }}
                    </ul>
                {% endif %}
            </div>
            <div class="password">
                {{ form.password }} {{ form.password.label }}
                {% if form.password.errors %}
                    <ul class="errors">
                        {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        <div class="submit-login-btn">
            <input id="login-btn" type="submit" value="Submit">
        </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

vault/templates/user.html
# Would like to eventually have each page be restricted to the corresponding user as well as admin. The 'profile' could show info like earnings over different periods - by week, month, YTD (maybe even average for all Fridays or Saturdays?). Other possibilities include average shift time, ytd wage hour (let users add in their hourly to compute?) user selected avatars?
{% extends 'layout.html' %}

{% block page_content %}
    <h1>User: {{ user.username }}</h1>
    <hr>
{% endblock %}

vault/templates/view_report.html
{% extends "layout.html" %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    <div class="row no-gutters" id="report-content-row">
        <div class="col-md-2 col-sm-1"></div>
        <div class="col-md-8 col-sm-10">
            <h1 class="page-header">REVIEW REPORT</h1>
            <form action="{{ url_for('main.submit_report') }}" method="post" id="submit-report-form">
                <div class="row no-gutters">
                    <div class="col-12" id="shift-date">
                        <h2>{{ stringify_date(shift.start_date) }}</h2>
                    </div>
                    <div class="col report-details">
                        <h4 class="report-details-h4">TIP HOURS: {{ shift.tip_hours|round(2) }}</h4>
                    </div>
                    <div class="col report-details">
                        <h4 class="report-details-h4">CASH TIP POOL: {{ shift.cash_tip_pool }}</h4>
                    </div>
                    <div class="col report-details">
                        <h4 class="report-details-h4">CASH TIP WAGE: {{ shift.cash_tip_wage|round(2) }}</h4>
                    </div>
                    <div class="col report-details">
                        <h4 class="report-details-h4">CC TIP POOL: {{ shift.cred_tip_pool }}</h4>
                    </div>
                    <div class="col report-details">
                        <h4 class="report-details-h4">CC TIP WAGE: {{ shift.cred_tip_wage|round(2) }}</h4>
                    </div>
                    <div class="col-12" id="report-tips">
                        <table class="table table-bordered table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="row" colspan="5">CC ONLY TOTALS</th>
                                </tr>
                                <tr>
                                    <th class="col col-th" scope="col">EMPLOYEE</th>
                                    <th class="col col-th" scope="col">SHIFT HOURS</th>
                                    <th class="col col-th" scope="col">ROLE</th>
                                    <th class="col col-th" scope="col">TIP HOURS</th>
                                    <th class="col col-th" scope="col">TOTAL</th>
                                </tr>
                            </thead>
                              {% for emp in shift.staff|list + shift.alt_staff|list |sort(attribute='first_name') %}
                                {% if emp.tip_hours > 0 %}
                                    <tr>
                                        <th class='th-dark' scope="row">{{ emp.first_name }}</th>
                                        <td class="td-dark">{{ emp.shift_hours }}</td>
                                        {% if emp.tip_role == 'SERVICE' %}
                                            <td class="td-dark">Service (x1.00)</td>
                                        {% elif emp.tip_role == 'SUPPORT' %}
                                            <td class="td-dark">Support (x0.65)</td>
                                        {% endif %}
                                        <td class="td-dark">{{ emp.tip_hours|round(2) }}</td>
                                        <td class="td-dark">{{ emp.cred_tips|round(2) }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </table>
                    </div>
                    <div class="col-12" id="cash-tips">
                        <table class="table table-bordered table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="row" colspan="5">CASH TOTALS</th>
                                </tr>
                                <tr>
                                    <th class="col col-th" scope="col">EMPLOYEE</th>
                                    <th class="col col-th" scope="col">SHIFT HOURS</th>
                                    <th class="col col-th" scope="col">ROLE</th>
                                    <th class="col col-th" scope="col">TIP HOURS</th>
                                    <th class="col col-th" scope="col">TOTAL</th>
                                </tr>
                            </thead>
                              {% for emp in shift.staff|list + shift.alt_staff|list |sort(attribute='first_name') %}
                                {% if emp.tip_hours > 0 %}
                                    <tr>
                                        <th class='th-dark' scope="row">{{ emp.first_name }}</th>
                                        <td class="td-dark">{{ emp.shift_hours }}</td>
                                        {% if emp.tip_role == 'SERVICE' %}
                                            <td class="td-dark">Service (x1.00)</td>
                                        {% elif emp.tip_role == 'SUPPORT' %}
                                            <td class="td-dark">Support (x0.65)</td>
                                        {% endif %}
                                        <td class="td-dark">{{ emp.tip_hours|round(2) }}</td>
                                        <td class="td-dark">{{ emp.cash_tips|round(2) }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </table>
                    </div>
                    <div class="col-12" id="submit-to-db-div">
                        <div class="row no-gutters">
                            <div class="col-12 center-block" id="report-btn-div">
                                <button class="button btn btn-info center-block" type="submit" id="report-btn">OMG PRAY THIS WORKS</button>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="shift_data" id="shift_data" value="{{ shift }}">
                <input type="hidden" name="emp_data" id="emp_data" value="{{ shift.staff }}">
            </form>
        </div>
        <div class="col-md-2 col-sm-1"></div>
    </div>

{% endblock %}